/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BowlRouteImport } from './routes/bowl'
import { Route as ClimbRouteImport } from './routes/climb'
import { Route as PresentRouteImport } from './routes/present'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlRoute = BowlRouteImport.update({
  id: '/bowl',
  path: '/bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const ClimbRoute = ClimbRouteImport.update({
  id: '/climb',
  path: '/climb',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentRoute = PresentRouteImport.update({
  id: '/present',
  path: '/present',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bowl': typeof BowlRoute
  '/climb': typeof ClimbRoute
  '/present': typeof PresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bowl': typeof BowlRoute
  '/climb': typeof ClimbRoute
  '/present': typeof PresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bowl': typeof BowlRoute
  '/climb': typeof ClimbRoute
  '/present': typeof PresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bowl' | '/climb' | '/present'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bowl' | '/climb' | '/present'
  id: '__root__' | '/' | '/bowl' | '/climb' | '/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BowlRoute: typeof BowlRoute
  ClimbRoute: typeof ClimbRoute
  PresentRoute: typeof PresentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowl': {
      id: '/bowl'
      path: '/bowl'
      fullPath: '/bowl'
      preLoaderRoute: typeof BowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/climb': {
      id: '/climb'
      path: '/climb'
      fullPath: '/climb'
      preLoaderRoute: typeof ClimbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/present': {
      id: '/present'
      path: '/present'
      fullPath: '/present'
      preLoaderRoute: typeof PresentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BowlRoute: BowlRoute,
  ClimbRoute: ClimbRoute,
  PresentRoute: PresentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
